name: Run tests and release
on:
  push:
    branches:
      - main

jobs:
  release:
    uses: slyngshot-al/github-shared-actions/.github/workflows/helm-release-to-main.yaml@main
    secrets: inherit
    with:
      go_version: 1.23.0
