name: qa-uat-tag

on:
  push:
    tags:
      - '*-qa'
      - '*-uat'

jobs:
  release:
    uses: slyngshot-al/github-shared-actions/.github/workflows/helm-release-to-qa-uat.yaml@main
    secrets: inherit
